### ISSUE TITLE
Hi shariq

### ISSUE THREAD

**Issue by ialcuaz** [ialcuaz/nodejs-express-news-and-stuff#1]
@shariqazz Sorry, was too busy (relaxing) but ready to get back into the swing of things. You or I could push a skeleton onto the repo like with 310, then just work on it when we feel like it I suppose.

**Comment by shariqazz** [comment]
hey dude. Lol don't worry about it ive been taking it easy too... Yeah we
can do that but have we finalized what we're working on?

On Sat, Aug 29, 2015 at 8:20 PM, Ito Mikael Alcuaz <notifications@github.com

**Comment by ialcuaz** [comment]
Don't think so, but the parsing will be good practice either way so maybe
we can just start with that. CNN, CBC, and BBC have apis we can use. I'm in
whistler right now, but will be back sept. 5, I think school starts on the
8th? You have the adv. os class after my class on the same room so maybe I
can stay behind and we'll talk about it a bit more then?

**Comment by shariqazz** [comment]
lets meet on the 8th after classes

On Sun, Aug 30, 2015 at 8:40 PM, Ito Mikael Alcuaz <notifications@github.com

**Comment by ialcuaz** [comment]
The 8th is imagine day so there are no classes until the 9th I believe
